stages:
    - build
    - test

build-4.07:
    stage: build
    image: ocaml/opam2:4.07
    script:
        - opam pin add -n .
        - opam depext -i .
        - opam install . --deps-only --with-test
        - dune build @install
    cache:
        paths:
            - _build

test-4.07:
    stage: test
    image: ocaml/opam2:4.07
    script:
        - dune runtest
