ocaml-4.07:
    stage: build
    image: ocaml/opam2:4.07
    script:
        - opam pin add -n .
        - opam depext softcheck
        - opam install . --deps-only --with-test
        - dune build @install
        - dune runtest
